# Generated by Django 6.0 on 2025-12-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flavor', models.CharField(blank=True, max_length=100)),
                ('protein_content', models.CharField(blank=True, max_length=50)),
                ('calories', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Protein Bar',
                'verbose_name_plural': 'Protein Bars',
            },
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('serving_size', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Supplement',
                'verbose_name_plural': 'Supplements',
            },
        ),
    ]
